const colors = require("tailwindcss/colors");
module.exports = {
  mode: "jit",
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      backgroundImage:   {
        sequoia: "linear-gradient( 229.7deg, #fdfdfe 14.85 % , #ffbb88 20.61 % , #ff7cba 26.17 % , #887bff 31.93%, #03c7f6 46.54 % , #0f1014 54.36%)",
      },
      colors: {
        //Moonlight
        moonlightBase: "#0F1014",
        moonlightInterface: "#111216",
        moonlightOverlay: "#131317",
        moonlightSoft: "#43444D",
        moonlightSlight: "#575861",
        moonlightText: "#868690",
        moonlightFocusLow: "#121216",
        moonlightFocusMedium: "#1A1B1F",
        moonlightFocusHigh: "#1F1F24",

        moonlightMetal: "#697078",
        moonlightStone: "#BFBBBB",
        moonlightOrange: "#FFBB88",
        moonlightPink: "#FF7CBA",
        moonlightIndigo: "#887BFF",
        moonlightBlue: "#03C7F6",

        //desaturated
        desaturatedBase: "#151516",
        desaturatedInterface: "#161517",
        desaturatedOverlay: "#161617",
        desaturatedSoft: "#55565C",
        desaturatedSlight: "#63636A",
        desaturatedText: "#828289",
        desaturatedFocusLow: "#161517",
        desaturatedFocusMedium: "#181819",
        desaturatedFocusHigh: "#19191B",

        desaturatedMetal: "#92979D",
        desaturatedStone: "#D1CECE",
        desaturatedOrange: "#FFCEA9",
        desaturatedPink: "#FFA0CD",
        desaturatedIndigo: "#A9A0FF",
        desaturatedBlue: "#A6EBFC",
        //monochrome

        monochromeKashmir: "#626983",
        monochromeSlate: "#7C829D",
        monochromeLogan: "#999EB2",
        monochromeCadet: "#B6BAC8",
        monochromeCat: "#D3D5DE",
        monochromeCloud: "#E2E4ED",
      },
      fontFamily: {
        sans: [
          '"NeueHaasDisplayBlack"',
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
        display: [
          '"NeueHaasDisplayBlack"',
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
        ds: [
          '"NeueHaasGroteskDisp Pro Md"',
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],

      },

    },
  },
  plugins: [],
};
